on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' && contains(github.event.comment.body, '/claim') && contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "yolo"
         echo $username
         echo $labels
        env:
          username: ${{ github.actor }}
      
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          assignees: ${{ github.actor }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
