on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' && contains(github.event.comment.body, '/claim')
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "yolo"
       echo $username
       echo $labels
    env:
      username: ${{ github.actor }}
      labels: ${{ github.event.issue.labels }}
