on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' 
      && contains(github.event.comment.body, '/claim') 
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
         echo "yolo"
         echo $username
         echo ${{ github.actor }}
         echo ${{ github.event.issue }}
        env:
          username: ${{ github.actor }}
      
      - uses: pozil/auto-assign-issue@v1
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           assignees: ${{ github.actor }}

      - name: addlabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: "Status: Assigned"
          type: add
      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: "Status: Available"
          type: remove
