on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' 
      && contains(github.event.comment.body, '/claim') 
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
         echo "yolo"
         echo $username
         echo ${{ github.actor }}
         echo ${{ github.event.issue }}
        env:
          username: ${{ github.actor }}
      
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({...context.issue, labels: ['invalid']})


      - uses: pozil/auto-assign-issue@v1
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           assignees: ${{ github.actor }}

