on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' 
      && contains(github.event.comment.body, '/claim') 
      && contains(github.event.issue.labels.*.name, 'Status:\ Available')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          just_labels: ${{ toJson(github.event.issue.labels) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$just_labels"
      - run: |
         echo "yolo"
         echo $username
         echo ${{ github.actor }}
         echo ${{ github.event.issue }}
        env:
          username: ${{ github.actor }}
      
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Status: Accepted']
            })
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Status: Available']
            })

      - uses: pozil/auto-assign-issue@v1
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           assignees: ${{ github.actor }}

