on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' 
      && contains(github.event.comment.body, '/claim') 
      && contains(toJson(github.event.issue.labels), 'Available')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          just_labels: ${{ toJson(github.event.issue.labels) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$just_labels"
      - run: |
         echo "yolo"
         echo $username
         echo ${{ github.actor }}
         echo ${{ github.event.issue }}
        env:
          username: ${{ github.actor }}
      
      - uses: actions/github-script@0.9.0
        env:
          username: ${{ github.actor }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Status: Accepted']
              })
            await github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Status: Available'
              })
            await github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [process.env.username]
              })
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Assigned to @'+context.payload.sender.login+'\n Please submit a PR with your solution'
            })
