on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' && contains(github.event.comment.body, '/claim')
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "yolo"
       echo $username
    env:
      username: ${{ github.actor }}

  always_job:
    name: Always run job
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow to fail when all other jobs are skipped."
