on: 
  issue_comment:
    types: [created]
name: Claim
jobs:
  assign:
    name: Assign
    if: github.event.issue.pull_request == '' 
      && contains(github.event.comment.body, '/claim') 
      && contains(github.event.issue.labels.*.name, 'bug')
      && github.event.action == 'unassigned'
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "yolo"
         echo $username
         echo ${{ github.actor }}
         echo ${{ github.event.issue }}
        env:
          username: ${{ github.actor }}
      
      - uses: pozil/auto-assign-issue@v1
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           assignees: ${{ github.actor }}
